[32mINFO[0m:     [09-10-2023 12:39:56] Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [09-10-2023 12:39:57] Starting component System
[36mDEBUG[0m:    [09-10-2023 12:39:57] Starting component Posthog
[36mDEBUG[0m:    [09-10-2023 12:39:57] Starting component SqliteDB
[36mDEBUG[0m:    [09-10-2023 12:39:57] Starting component LocalSegmentManager
[36mDEBUG[0m:    [09-10-2023 12:39:57] Starting component SegmentAPI
[32mINFO[0m:     [09-10-2023 12:39:57] Started server process [[36m61563[0m]
[32mINFO[0m:     [09-10-2023 12:39:57] Waiting for application startup.
[32mINFO[0m:     [09-10-2023 12:39:57] Application startup complete.
[32mINFO[0m:     [09-10-2023 12:39:57] Uvicorn running on [1mhttp://0.0.0.0:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [09-10-2023 12:45:47] 127.0.0.1:58519 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [09-10-2023 12:45:47] 127.0.0.1:58519 - "GET /favicon.ico HTTP/1.1" 404
[32mINFO[0m:     [09-10-2023 12:46:14] 127.0.0.1:59566 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [09-10-2023 12:46:14] 127.0.0.1:59566 - "GET /favicon.ico HTTP/1.1" 404
[32mINFO[0m:     [09-10-2023 12:49:08] 127.0.0.1:51315 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:49:34] 127.0.0.1:52614 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:49:52] 127.0.0.1:53484 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:50:26] 127.0.0.1:55021 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:51:15] 127.0.0.1:57093 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:53:19] 127.0.0.1:62121 - "POST /api/v1/collections HTTP/1.1" 200
[36mDEBUG[0m:    [09-10-2023 12:53:31] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [09-10-2023 12:53:31] 127.0.0.1:62597 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/add HTTP/1.1" 201
[32mINFO[0m:     [09-10-2023 12:53:37] 127.0.0.1:62851 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/add HTTP/1.1" 201
[32mINFO[0m:     [09-10-2023 12:54:12] 127.0.0.1:64295 - "GET /api/v1/heartbeat HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:54:12] 127.0.0.1:64296 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:54:29] 127.0.0.1:65007 - "GET /api/v1/heartbeat HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:54:31] 127.0.0.1:65007 - "GET /api/v1/collections/openapi HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:54:31] 127.0.0.1:65063 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:56:43] 127.0.0.1:53183 - "GET /api/v1/heartbeat HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:56:45] 127.0.0.1:53183 - "GET /api/v1/collections/openapi HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:56:45] 127.0.0.1:53210 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:57:03] 127.0.0.1:53567 - "POST /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [09-10-2023 12:57:04] Expected where value for $and or $or to be a list with at least two where expressions, got [{'provider': {'$eq': 'Stripe API'}}]
Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 58, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 309, in get_nearest_neighbors
    nnresult = self._api._query(
               ^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/api/segment.py", line 506, in _query
    where = validate_where(where) if where is not None and len(where) > 0 else where
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/api/types.py", line 223, in validate_where
    raise ValueError(
ValueError: Expected where value for $and or $or to be a list with at least two where expressions, got [{'provider': {'$eq': 'Stripe API'}}]
[32mINFO[0m:     [09-10-2023 12:57:04] 127.0.0.1:53567 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 500
[32mINFO[0m:     [09-10-2023 12:57:39] 127.0.0.1:54249 - "POST /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [09-10-2023 12:57:41] Expected where value for $and or $or to be a list with at least two where expressions, got [{'provider': {'$eq': 'Stripe API'}}]
Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 58, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 309, in get_nearest_neighbors
    nnresult = self._api._query(
               ^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/api/segment.py", line 506, in _query
    where = validate_where(where) if where is not None and len(where) > 0 else where
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/api/types.py", line 223, in validate_where
    raise ValueError(
ValueError: Expected where value for $and or $or to be a list with at least two where expressions, got [{'provider': {'$eq': 'Stripe API'}}]
[32mINFO[0m:     [09-10-2023 12:57:41] 127.0.0.1:54249 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 500
[32mINFO[0m:     [09-10-2023 12:58:04] 127.0.0.1:54732 - "POST /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [09-10-2023 12:58:05] Expected where value for $and or $or to be a list with at least two where expressions, got [{'provider': {'$eq': 'Stripe API'}}]
Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 58, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 309, in get_nearest_neighbors
    nnresult = self._api._query(
               ^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/api/segment.py", line 506, in _query
    where = validate_where(where) if where is not None and len(where) > 0 else where
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sudhanshugautam/.asdf/installs/python/3.11.4/lib/python3.11/site-packages/chromadb/api/types.py", line 223, in validate_where
    raise ValueError(
ValueError: Expected where value for $and or $or to be a list with at least two where expressions, got [{'provider': {'$eq': 'Stripe API'}}]
[32mINFO[0m:     [09-10-2023 12:58:06] 127.0.0.1:54732 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 500
[32mINFO[0m:     [09-10-2023 12:59:50] 127.0.0.1:56719 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 12:59:51] 127.0.0.1:56719 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 13:09:02] 127.0.0.1:53534 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [09-10-2023 13:09:04] 127.0.0.1:53534 - "POST /api/v1/collections/38a67817-ef95-470c-b7ed-94a38f27605d/query HTTP/1.1" 200
